(()=>{'use strict';
const canvas=document.getElementById('world'),stats=document.getElementById('stats'),title=document.getElementById('title'),play=document.getElementById('play'),log=document.getElementById('log'),loadBar=document.querySelector('#load i');
const gl=canvas.getContext('webgl2',{alpha:false,antialias:true,depth:true,powerPreference:'high-performance'});if(!gl){log.textContent='WebGL2 is required.';throw new Error('WebGL2 unavailable');}
const vertex=`#version 300 es
precision highp float;
layout(location=0)in vec3 aPosition;layout(location=1)in vec3 aNormal;layout(location=2)in vec3 iCenter;layout(location=3)in float iSize;layout(location=4)in vec3 iColor;
uniform vec2 uResolution;uniform vec3 uCamera;uniform vec2 uLook;uniform float uDay;
out vec3 vColor;out vec3 vNormal;out float vDepth;
void main(){float cy=cos(uLook.x),sy=sin(uLook.x),cp=cos(uLook.y),sp=sin(uLook.y);vec3 forward=normalize(vec3(sy*cp,sp,-cy*cp)),right=normalize(cross(forward,vec3(0,1,0))),up=cross(right,forward);vec3 world=iCenter+aPosition*iSize,rel=world-uCamera;float vx=dot(rel,right),vy=dot(rel,up),vz=dot(rel,forward);float n=.05,f=650.0,tanHalf=.7002,aspect=uResolution.x/uResolution.y;gl_Position=vec4(vx/(tanHalf*aspect),vy/tanHalf,((f+n)/(f-n))*vz-(2.0*f*n)/(f-n),vz);vColor=iColor;vNormal=aNormal;vDepth=vz;}`;
const fragment=`#version 300 es
precision highp float;in vec3 vColor;in vec3 vNormal;in float vDepth;out vec4 fragColor;uniform float uDay;
void main(){vec3 sun=normalize(vec3(.55,.82,.32));float wrap=.5+.5*dot(normalize(vNormal),sun),hemi=.5+.5*normalize(vNormal).y;float light=.58+.23*wrap+.19*hemi;vec3 color=vColor*light;vec3 fogColor=vec3(.47,.70,.88);float fog=1.0-exp(-max(vDepth,0.0)*.0042);color=mix(color,fogColor,clamp(fog,0.0,.78));color=pow(color,vec3(.94));fragColor=vec4(color,1);}`;
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vertex));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));gl.useProgram(program);
const uniforms={resolution:gl.getUniformLocation(program,'uResolution'),camera:gl.getUniformLocation(program,'uCamera'),look:gl.getUniformLocation(program,'uLook'),day:gl.getUniformLocation(program,'uDay')};
const cubePositions=[],cubeNormals=[];function face(normal,a,b,c,d){for(const p of[a,b,c,a,c,d]){cubePositions.push(...p);cubeNormals.push(...normal);}}
face([1,0,0],[.5,-.5,-.5],[.5,.5,-.5],[.5,.5,.5],[.5,-.5,.5]);face([-1,0,0],[-.5,-.5,.5],[-.5,.5,.5],[-.5,.5,-.5],[-.5,-.5,-.5]);face([0,1,0],[-.5,.5,-.5],[-.5,.5,.5],[.5,.5,.5],[.5,.5,-.5]);face([0,-1,0],[-.5,-.5,.5],[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5]);face([0,0,1],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5],[-.5,-.5,.5]);face([0,0,-1],[-.5,-.5,-.5],[-.5,.5,-.5],[.5,.5,-.5],[.5,-.5,-.5]);
const vao=gl.createVertexArray();gl.bindVertexArray(vao);function staticAttribute(location,data){const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);gl.enableVertexAttribArray(location);gl.vertexAttribPointer(location,3,gl.FLOAT,false,0,0);}staticAttribute(0,cubePositions);staticAttribute(1,cubeNormals);
const instanceBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,instanceBuffer);const stride=7*4;gl.enableVertexAttribArray(2);gl.vertexAttribPointer(2,3,gl.FLOAT,false,stride,0);gl.vertexAttribDivisor(2,1);gl.enableVertexAttribArray(3);gl.vertexAttribPointer(3,1,gl.FLOAT,false,stride,3*4);gl.vertexAttribDivisor(3,1);gl.enableVertexAttribArray(4);gl.vertexAttribPointer(4,3,gl.FLOAT,false,stride,4*4);gl.vertexAttribDivisor(4,1);
gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.clearColor(.47,.70,.88,1);

const workerSource=String.raw`
'use strict';
const PI=Math.PI,MAX_VOXELS=40000,STRIDE=7;
let out,minVoxel,resourceCounts;
const colors={grass:[.23,.49,.27],grass2:[.35,.59,.34],dirt:[.43,.30,.22],stone:[.47,.48,.55],stone2:[.61,.62,.70],bark:[.31,.20,.16],wood:[.43,.28,.20],leaf:[.13,.45,.17],leaf2:[.24,.62,.22],fern:[.20,.50,.23],purple:[.48,.31,.58],quartz:[.69,.70,.78],snow:[.89,.89,.86]};
function fract(x){return x-Math.floor(x)}function hash2(x,z,s=0){return fract(Math.sin(x*127.1+z*311.7+s*17.17)*43758.5453123)}function noise2(x,z){let ix=Math.floor(x),iz=Math.floor(z),fx=fract(x),fz=fract(z);fx=fx*fx*(3-2*fx);fz=fz*fz*(3-2*fz);let a=hash2(ix,iz),b=hash2(ix+1,iz),c=hash2(ix,iz+1),d=hash2(ix+1,iz+1);return(a*(1-fx)+b*fx)*(1-fz)+(c*(1-fx)+d*fx)*fz}function fbm(x,z){let v=0,a=.56;for(let i=0;i<4;i++){v+=noise2(x,z)*a;let nx=.8*x-.6*z,nz=.6*x+.8*z;x=nx*2.03+17.1;z=nz*2.03+17.1;a*=.47}return v}
function terrainHeight(x,z){let land=fbm(x*.012,z*.012),detail=noise2(x*.065-20,z*.065+31);return 1.5+land*15+detail*.8}
function add(x,y,z,size,color,id){if(out.length/STRIDE>=MAX_VOXELS)return false;out.push(x,y,z,size,color[0],color[1],color[2]);if(size<minVoxel)minVoxel=size;resourceCounts[id]=(resourceCounts[id]||0)+1;return true}
function terrainNode(cx,cz,size,camera,depth){let dx=cx-camera.x,dz=cz-camera.z,dist=Math.hypot(dx,dz);if(dist>330||out.length/STRIDE>=MAX_VOXELS)return;let target=dist<22?.5:dist<55?1:dist<115?2:dist<210?4:8;if(size>target&&depth<9){let h=size*.5,q=size*.25;terrainNode(cx-q,cz-q,h,camera,depth+1);terrainNode(cx+q,cz-q,h,camera,depth+1);terrainNode(cx-q,cz+q,h,camera,depth+1);terrainNode(cx+q,cz+q,h,camera,depth+1);return}let y=terrainHeight(cx,cz),grain=hash2(Math.floor(cx/Math.max(size,1)),Math.floor(cz/Math.max(size,1))),color=y>17?colors.snow:grain>.92?colors.stone:grain>.62?colors.grass2:colors.grass;add(cx,y-size*.5,cz,size,color,'terrain')}
function capsule(px,py,pz,ax,ay,az,bx,by,bz,r){let pax=px-ax,pay=py-ay,paz=pz-az,bax=bx-ax,bay=by-ay,baz=bz-az,h=Math.max(0,Math.min(1,(pax*bax+pay*bay+paz*baz)/(bax*bax+bay*bay+baz*baz)));return Math.hypot(pax-bax*h,pay-bay*h,paz-baz*h)-r}
function ellipsoid(x,y,z,rx,ry,rz){let k0=Math.hypot(x/rx,y/ry,z/rz),k1=Math.hypot(x/(rx*rx),y/(ry*ry),z/(rz*rz));return k0*(k0-1)/Math.max(k1,.0001)}
function fractalSurface(x,y,z,scale){let v=0,a=.35,f=1;for(let i=0;i<7;i++){if(1/f<scale*.35)break;v+=Math.sin(x*f*1.7+Math.sin(z*f*1.3))*Math.sin(y*f*1.9-z*f*.7)*a;f*=2.03;a*=.48}return v}
function makeTree(seed,conifer=false){let segments=[[0,0,0,0,10,0,.72]],spheres=[];function branch(x,y,z,len,r,angle,tilt,level){if(level>3)return;let bx=x+Math.cos(angle)*Math.cos(tilt)*len,by=y+Math.sin(tilt)*len,bz=z+Math.sin(angle)*Math.cos(tilt)*len;segments.push([x,y,z,bx,by,bz,r]);if(level>=2)spheres.push([bx,by,bz,len*(conifer?.52:.70)]);for(let c=0;c<2;c++){let a=angle+(c-.5)*(.78+hash2(level,c,seed)*.3)+2.39996*level,t=Math.min(1.25,tilt+.2+(hash2(c,level,seed)-.5)*.16);branch(bx,by,bz,len*(.60+hash2(level,c,seed)*.05),r*.62,a,t,level+1)}}let tiers=conifer?4:3,count=conifer?3:2;for(let i=0;i<tiers;i++){let y=2.7+i*1.35;for(let c=0;c<count;c++)branch(0,y,0,(conifer?3.0:2.5)*(1-i*.08),.24,c*PI*2/count+i*.41,conifer?.22:.42,1)}return{segments,spheres}}
function treeSample(local,scale,tree){let best=1e9,color=colors.bark;for(const s of tree.segments){let d=capsule(local.x,local.y,local.z,...s);if(d<best){best=d;color=colors.bark}}for(const s of tree.spheres){let dx=local.x-s[0],dy=local.y-s[1],dz=local.z-s[2],raw=Math.hypot(dx,dy,dz)-s[3];if(raw<best+.22){let d=raw+fractalSurface(dx,dy,dz,scale)*.18;if(d<best){best=d;color=hash2(Math.floor(local.x/Math.max(scale,.04)),Math.floor(local.z/Math.max(scale,.04)))>.55?colors.leaf2:colors.leaf}}}return[best,color]}
function rockSample(p,scale){let d=ellipsoid(p.x,p.y,p.z,2.5,1.8,2.2)+fractalSurface(p.x,p.y,p.z,scale)*.22;return[d,hash2(Math.floor(p.x/Math.max(scale,.05)),Math.floor(p.z/Math.max(scale,.05)))>.6?colors.stone2:colors.stone]}
function crystalSample(p,sides){let angle=Math.atan2(p.z,p.x),sector=PI*2/sides,local=((angle+PI/sides)%sector+sector)%sector-PI/sides,radial=Math.hypot(p.x,p.z)*Math.cos(local)/Math.cos(PI/sides),height=4.8,taper=.72*(1-Math.max(0,p.y-height*.68)/(height*.32)),d=Math.max(radial-Math.max(.06,taper),Math.abs(p.y-height*.48)-height*.52);return[d,sides===5?colors.quartz:colors.purple]}
function fernSample(p){let best=capsule(p.x,p.y,p.z,0,0,0,0,2.3,0,.08);for(let i=0;i<7;i++){let a=i*PI*2/7,tx=Math.cos(a)*1.7,ty=1.8+Math.sin(i*2.1)*.22,tz=Math.sin(a)*1.7,d=capsule(p.x,p.y,p.z,0,.15,0,tx,ty,tz,.055);if(d<best)best=d;for(let j=2;j<8;j++){let t=j/8,cx=tx*t,cy=ty*t,cz=tz*t,side=.52*Math.sin(PI*t),nx=Math.cos(a+PI/2),nz=Math.sin(a+PI/2);d=Math.min(capsule(p.x,p.y,p.z,cx,cy,cz,cx+nx*side,cy+.05,cz+nz*side,.045),capsule(p.x,p.y,p.z,cx,cy,cz,cx-nx*side,cy+.05,cz-nz*side,.045));if(d<best)best=d}}return[best,colors.fern]}
function bushSample(p,scale){let best=1e9,rough=fractalSurface(p.x,p.y,p.z,scale)*.10;for(let i=0;i<9;i++){let a=i*2.39996,rad=.55*Math.sqrt(i),cx=Math.cos(a)*rad,cy=.65+(i%3)*.38,cz=Math.sin(a)*rad,d=Math.hypot(p.x-cx,p.y-cy,p.z-cz)-.72+rough;if(d<best)best=d}return[best,colors.leaf]}
function emitResource(def,camera,focal){let centerDistance=Math.hypot(def.cx-camera.x,def.cy-camera.y,def.cz-camera.z),minSize=centerDistance<2?.03125:centerDistance<6?.0625:centerDistance<12?.125:.25,pixelTarget=def.id==='oak'||def.id==='fir'?10:def.id==='blueberry'?8:6,stack=[[def.cx,def.cy,def.cz,def.size,0]],visits=0,leaves=0;while(stack.length&&out.length/STRIDE<MAX_VOXELS&&visits++<6000&&leaves<1600){let [cx,cy,cz,size,depth]=stack.pop(),dx=cx-camera.x,dy=cy-camera.y,dz=cz-camera.z,dist=Math.max(.2,Math.hypot(dx,dy,dz));if(dist>360)continue;let projected=size*focal/dist,local={x:cx-def.ox,y:cy-def.oy,z:cz-def.oz},sample=def.sample(local,size),radius=size*.866;if(sample[0]>radius||sample[0]<-radius*1.05)continue;if(projected<=pixelTarget||size<=minSize||depth>=13){if(sample[0]<=radius*.38&&add(cx,cy,cz,size,sample[1],def.id))leaves++;continue}let h=size*.5,q=size*.25;for(let z=-1;z<=1;z+=2)for(let y=-1;y<=1;y+=2)for(let x=-1;x<=1;x+=2)stack.push([cx+x*q,cy+y*q,cz+z*q,h,depth+1])}}
onmessage=e=>{let start=performance.now(),camera=e.data.camera,height=e.data.height,focal=height*.5/Math.tan(35*PI/180);out=[];minVoxel=1e9;resourceCounts={};for(let z=-224;z<=224;z+=64)for(let x=-224;x<=224;x+=64)terrainNode(x,z,64,camera,0);
let oak=makeTree(1307,false),fir=makeTree(2081,true);let resources=[
 {id:'oak',ox:0,oy:terrainHeight(0,-14),oz:-14,cx:0,cy:terrainHeight(0,-14)+8,cz:-14,size:16,sample:(p,s)=>treeSample(p,s,oak)},
 {id:'fir',ox:-13,oy:terrainHeight(-13,-25),oz:-25,cx:-13,cy:terrainHeight(-13,-25)+8,cz:-25,size:16,sample:(p,s)=>treeSample(p,s,fir)},
 {id:'rock',ox:-5,oy:terrainHeight(-5,-7)+1,oz:-7,cx:-5,cy:terrainHeight(-5,-7)+1,cz:-7,size:8,sample:rockSample},
 {id:'crystal5',ox:6,oy:terrainHeight(6,-10),oz:-10,cx:6,cy:terrainHeight(6,-10)+3,cz:-10,size:8,sample:p=>crystalSample(p,5)},
 {id:'crystal7',ox:11,oy:terrainHeight(11,-17),oz:-17,cx:11,cy:terrainHeight(11,-17)+3,cz:-17,size:8,sample:p=>crystalSample(p,7)},
 {id:'fern',ox:3,oy:terrainHeight(3,-5),oz:-5,cx:3,cy:terrainHeight(3,-5)+1.4,cz:-5,size:4,sample:fernSample},
 {id:'blueberry',ox:-3,oy:terrainHeight(-3,-4),oz:-4,cx:-3,cy:terrainHeight(-3,-4)+1.2,cz:-4,size:4,sample:bushSample}
 ];for(const resource of resources)emitResource(resource,camera,focal);let data=new Float32Array(out);postMessage({buffer:data.buffer,count:data.length/STRIDE,minVoxel,resourceCounts,ms:performance.now()-start},[data.buffer])};`;

const workerUrl=URL.createObjectURL(new Blob([workerSource],{type:'text/javascript'})),worker=new Worker(workerUrl);let voxelCount=0,minVoxel=0,generationMs=0,resourceCounts={},workerBusy=false,dirty=true,lastBuild={x:1e9,z:1e9};
const state={running:false,x:0,y:8,z:12,yaw:0,pitch:-.09,vy:0,onGround:false,crawl:false,keys:new Set(),last:performance.now(),fps:0,frameMs:16};
function requestVoxels(){if(workerBusy){dirty=true;return}workerBusy=true;dirty=false;log.textContent='Traversing projected octree nodes in background…';loadBar.style.width='68%';worker.postMessage({camera:{x:state.x,y:state.y,z:state.z},width:canvas.width,height:canvas.height});lastBuild={x:state.x,z:state.z};}
worker.onmessage=e=>{const data=new Float32Array(e.data.buffer);gl.bindBuffer(gl.ARRAY_BUFFER,instanceBuffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW);voxelCount=e.data.count;minVoxel=e.data.minVoxel;generationMs=e.data.ms;resourceCounts=e.data.resourceCounts;workerBusy=false;loadBar.style.width='100%';log.textContent=`Tagged voxel buffer ready: ${voxelCount.toLocaleString()} visible leaves\nSmallest selected voxel: ${minVoxel.toFixed(4)} m`;if(play.disabled){play.disabled=false;play.textContent='Walk into the voxel world'}if(dirty)requestVoxels();};worker.onerror=e=>{workerBusy=false;log.textContent=`Voxel conversion failed: ${e.message}`;};
function hash2(x,z){let n=Math.sin(x*127.1+z*311.7)*43758.5453123;return n-Math.floor(n)}function noise2(x,z){let ix=Math.floor(x),iz=Math.floor(z),fx=x-ix,fz=z-iz;fx=fx*fx*(3-2*fx);fz=fz*fz*(3-2*fz);return(hash2(ix,iz)*(1-fx)+hash2(ix+1,iz)*fx)*(1-fz)+(hash2(ix,iz+1)*(1-fx)+hash2(ix+1,iz+1)*fx)*fz}function fbm(x,z){let v=0,a=.56;for(let i=0;i<4;i++){v+=noise2(x,z)*a;let nx=.8*x-.6*z,nz=.6*x+.8*z;x=nx*2.03+17.1;z=nz*2.03+17.1;a*=.47}return v}function ground(x,z){return 1.5+fbm(x*.012,z*.012)*15+noise2(x*.065-20,z*.065+31)*.8}
state.y=ground(state.x,state.z)+1.7;
function resize(){let scale=.78,w=Math.max(640,Math.floor(innerWidth*scale)),h=Math.max(360,Math.floor(innerHeight*scale));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h);dirty=true}}addEventListener('resize',resize,{passive:true});resize();requestVoxels();
function update(dt){let fx=Math.sin(state.yaw),fz=-Math.cos(state.yaw),rx=Math.cos(state.yaw),rz=Math.sin(state.yaw),mx=0,mz=0;if(state.keys.has('KeyW')){mx+=fx;mz+=fz}if(state.keys.has('KeyS')){mx-=fx;mz-=fz}if(state.keys.has('KeyA')){mx-=rx;mz-=rz}if(state.keys.has('KeyD')){mx+=rx;mz+=rz}let len=Math.hypot(mx,mz)||1,speed=state.crawl?1.6:4.6;state.x+=mx/len*speed*dt;state.z+=mz/len*speed*dt;let eye=state.crawl?.9:1.7,g=ground(state.x,state.z)+eye;state.vy-=10*dt;state.y+=state.vy*dt;if(state.y<=g){state.y=g;state.vy=0;state.onGround=true}else state.onGround=false;if(Math.hypot(state.x-lastBuild.x,state.z-lastBuild.z)>2)requestVoxels()}
function frame(now){let dt=Math.min(.05,(now-state.last)/1000);state.last=now;if(state.running)update(dt);resize();gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.bindVertexArray(vao);gl.uniform2f(uniforms.resolution,canvas.width,canvas.height);gl.uniform3f(uniforms.camera,state.x,state.y,state.z);gl.uniform2f(uniforms.look,state.yaw,state.pitch);gl.uniform1f(uniforms.day,12);if(voxelCount)gl.drawArraysInstanced(gl.TRIANGLES,0,36,voxelCount);state.frameMs=state.frameMs*.92+dt*1000*.08;state.fps=Math.round(1000/state.frameMs);stats.textContent=`${state.fps} fps · ${voxelCount.toLocaleString()} visible voxels\nsmallest ${minVoxel?minVoxel.toFixed(4):'—'} m · conversion ${generationMs.toFixed(1)} ms off-thread\nresource leaves ${Object.entries(resourceCounts).filter(([k])=>k!=='terrain').reduce((a,[,v])=>a+v,0).toLocaleString()} · xyz ${state.x.toFixed(1)}, ${state.y.toFixed(1)}, ${state.z.toFixed(1)}`;requestAnimationFrame(frame)}requestAnimationFrame(frame);
play.addEventListener('click',()=>{state.running=true;title.classList.add('hidden');canvas.requestPointerLock?.()});canvas.addEventListener('click',()=>{if(state.running&&document.pointerLockElement!==canvas)canvas.requestPointerLock?.()});addEventListener('mousemove',e=>{if(document.pointerLockElement!==canvas)return;state.yaw-=e.movementX*.0022;state.pitch=Math.max(-1.45,Math.min(1.45,state.pitch-e.movementY*.0022))});addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();document.pointerLockElement?document.exitPointerLock():canvas.requestPointerLock?.();return}if(e.code==='ShiftLeft'&&state.onGround){state.vy=4.65;state.onGround=false}if(e.code==='ControlLeft')state.crawl=true;if(e.code==='Escape'){state.running=false;title.classList.remove('hidden');document.exitPointerLock?.()}state.keys.add(e.code)});addEventListener('keyup',e=>{state.keys.delete(e.code);if(e.code==='ControlLeft')state.crawl=false});
})();
